name = "RegionalGrasslandVis"
uuid = "8dfe2b93-2724-4a97-a872-41e2c75779aa"
authors = ["Felix Nößler <felixnoessler@aol.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
